### ISSUE TITLE
Able to do /plotme home whilst in Combat Tag on EcoPvP

### ISSUE THREAD

**Issue by OhMyHam** [FlowzMC/Issues#30]
**Issue:**
On EcoPvp, whilst in combat tag you're able to get out of combat tag without losing any of your stuff by doing /plotme home.

**How to reproduce the problem:**
To reproduce the problem, you need to be put into Combat Tag and whilst in it, do /plotme home and it will bring you to your farm and out of the tag.

**Miscellaneous:** 
https://youtu.be/pnJ6FcOZYrk

**Comment by Dragonleet** [comment]
Fixed
